### PR TITLE
Add 10Pines

### PR DESCRIPTION
**Pull request by egutter**
Please review our [Contribution Guidelines](https://github.com/doomspork/elixir-companies/blob/master/CONTRIBUTING.md) to ensure your changes abides by it.

Changes should be made to the __end of the file__.

Review your changes and complete the checklist below.

- [X] Company name
- [X] Industry
- [X] Company location
- [X] Company description
- [X] How Elixir is used
- [X] GitHub / blog links
- [ ] Job listings

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @egutter!  😁

**Comment by egutter** [comment]
welcome @doomspork ! 😄  I haven't seen the changes on the site yet. Is the PR deployed automatically once merged or is there some manual deploy required?

**Comment by egutter** [comment]
ooops.. Sorry for that! My bad 😢 
Thanks for fixing it @doomspork !

**Comment by doomspork** [comment]
No problemo @egutter!  I hope you had a wonderful weekend and have a great week 😁

**Pull request merged**
