### PR TITLE
Fixing the build

### PR DESCRIPTION
**Pull request by svileng**
This is an attempt to fix the build by:

- Removing invalid github repo link;
- Removing duplicate company;
- Updating one company's URL

### CODE REVIEW

**Comment by svileng** [comment]
Another thing came up — a broken link to a job posting. It's easy to remove, but this will come back again and again, as job postings are taken down after the position is filled.

Could this check produce a warning rather than an error failing the build, if the link is not valid anymore? What do you think @doomspork?

**Comment by doomspork** [comment]
@svileng thank you for doing this ❤️ Could you resolve the conflicts so I can merge this?

This check definitely needs to be revisited.  It's pretty basic and truth be told, I'm not 100% sure what all it can do.  I'll bug @burden today who helped me set it up initially and see if we can't make some improvements.  I agree the failing build is annoying.

**Comment by doomspork** [comment]
@svileng I don't know what kind of bandwidth you have but if you're interested in helping out, I'd be happy to add you as a collaborator to the project.

There's definitely improvements we could make: #337 and #296 are just a few.  Many of the changes here can be ported to the forks like https://erlang-companies.org, https://julia-companies.org, and https://kotlin-companies.com which is pretty cool 😁

**Comment by svileng** [comment]
@doomspork I'd love to help but the next couple of weeks would be quite busy on my end; let's discuss it over email, I'll drop you a message and we'll take it from there 👍

**Pull request merged**
