### PR TITLE
Add support gettext

### PR DESCRIPTION
**Pull request by Nitrino**
Related with #493 

### Notes:

1. Did not add the gettext to the admin area, I think we do not need to translate it. Agree?
2. The project has `resources "/users", UserController` and templates, but does not have ` UserController`. I did not add a gettex to them, it seems they need to be deleted?
3. The list of industries is stored in the database, we need to think about its localization.

Quick sample translations:
localhost_4000_ (2)

### CODE REVIEW

**Comment by doomspork** [comment]
Howdy @Nitrino! This is _awesome_

1. Agreed. This part of the site needs some work anyways. 👍  I'd rather no waste people's time making it better.
1. We should delete that!
1. This is a good point. We need to think about this one a bit for a couple of reasons:
    1. If anything we want to make this list smaller; consolidate some industries. We've had a free issues opened about this in the past #252 
    1. Moving the industries into a file makes it easier for folks to think they can add their own industries, which happened _all the time_ before.
    1. Lastly, I'd very much like to avoid "wasting" translators time with things subject to too much flux.

**Comment by gemantzu** [comment]
@nitrino Thank you so much for your great effort. I am off decompressing a bit, I am going back to business tomorrow. I will check it up and all the other stuff that ppl are pushing towards us, I have to say, things are looking really good for this project :)

**Comment by brain-geek** [comment]
@doomspork Actually, if we want to limit industries, we can just hardcode it. This way nobody will create a new ones. :trollface: 

We can take some industry list tested by time, [like this one](https://www.nasdaq.com/screening/industries.aspx). Also, this will allow translating industries more easily.

**Comment by doomspork** [comment]
@brain-geek I fear that list is too small. What do you think about merging this and continuing the conversation RE: consolidating the list + moving it to a translatable place into a new issue?

**Comment by brain-geek** [comment]
@doomspork That would be an awesome idea! I support that. @Nitrino did a really good job, kudos to him!

**Comment by Nitrino** [comment]
Guys, I solved conflicts with master

**Comment by doomspork** [comment]
@Nitrino / @brain-geek now we need to create a few more issues, correct me if I'm wrong:

1. A strategy to identify and set the locale (url path, browser headers, where in the request flow...)
1. Translations 🎉

**Comment by Nitrino** [comment]
@doomspork Yep, right. 
More:
3. The ability to localize the description of companies. Need to discuss.
4. Localization of the list of industries.

**Comment by doomspork** [comment]
@Nitrino I'll get those created and tag you for comments 😁 

Thanks so much for all your help

**Pull request merged**
