### PR TITLE
Add Frame

### PR DESCRIPTION
**Pull request by stevedomin**
Please review our [Contribution Guidelines](https://github.com/doomspork/elixir-companies/blob/master/CONTRIBUTING.md) to ensure your changes abides by it.

Review your changes and complete the checklist below.

- [x] Company name
- [x] Company description
- [x] Company location
- [x] GitHub link
- [x] How Elixir is used
- [x] Sorted alphabetically

### CODE REVIEW

**Comment by stevedomin** [comment]
Frame's director of engineering (Chris Bell) announced the move on Twitter: https://twitter.com/cjbell_/status/931904584666308610

**Comment by doomspork** [comment]
Thanks @stevedomin!  You're so dang helpful and on top it, would you like be a contributor?

**Comment by stevedomin** [comment]
@doomspork what would it entails? (just want to make sure I don't overcommit, I've plenty of stuff on my plate already)

**Comment by doomspork** [comment]
@stevedomin no worries — I can appreciate being overextended myself 😀 

I was strictly speaking to giving you merge rights so you could add businesses as you find them and not have to worry about a PR but it's no trouble

**Comment by stevedomin** [comment]
@doomspork that sounds good, if that can save you some time I'm all for it. Maybe I'll find the time to merge a PR or two as well.

**Comment by doomspork** [comment]
You've been added!  Thanks for all your help @stevedomin.  I'm open to any suggestions you have as well to make the resource more useful.  😁

**Comment by stevedomin** [comment]
Will think about it! I always thought it would be nice to have an auto-updating count somewhere.

**Pull request merged**
