### PR TITLE
Add FunBox

### PR DESCRIPTION
**Pull request by vassilevsky**
Please review our [Contribution Guidelines](https://github.com/doomspork/elixir-companies/blob/master/CONTRIBUTING.md) to ensure your changes abides by it.

Changes should be made to the __end of the file__.

Review your changes and complete the checklist below.

- [x] Company name
- [x] Industry
- [x] Company location
- [x] Company description
- [x] How Elixir is used
- [x] GitHub / blog links
- [x] Job listings

### CODE REVIEW

**Comment by vassilevsky** [comment]
Please let me know if I should remove the reference to Ruby on Rails.

**Comment by doomspork** [comment]
No need @vassilevsky, this is great! 👍

**Comment by vassilevsky** [comment]
Thank you for accepting our humble company 😘 🇷🇺

**Comment by doomspork** [comment]
You're welcome @vassilevsky 👍

**Pull request merged**
